=== accelplatform/docker-stacks-cluster/data/juggling/project/schema/im-notice-mobile-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.intra-mart.jp/notice/mobile/config/im-notice-mobile-config"
  xmlns:tns="http://www.intra-mart.jp/notice/mobile/config/im-notice-mobile-config"
  xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" jaxb:version="2.0" elementFormDefault="qualified">

  <xsd:annotation>
    <xsd:appinfo>
      <jaxb:schemaBindings>
        <jaxb:package name="jp.co.intra_mart.system.notice.mobile.config"></jaxb:package>
      </jaxb:schemaBindings>
    </xsd:appinfo>
  </xsd:annotation>

  <xsd:element name="im-notice-mobile-config">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="proxy" type="tns:proxy" />
        <xsd:element name="asns" type="tns:asns" maxOccurs="unbounded" />
        <xsd:element name="fcm" type="tns:fcm" maxOccurs="unbounded" />
        <xsd:element name="push" type="tns:push" maxOccurs="unbounded" />
        <xsd:element name="max-push-subject-length" type="xsd:unsignedInt" />
        <xsd:element name="max-push-body-length" type="xsd:unsignedInt" />
      </xsd:sequence>
    </xsd:complexType>
    <xsd:unique name="unique-push-type">
      <xsd:selector xpath="tns:push" />
      <xsd:field xpath="@type" />
    </xsd:unique>
  </xsd:element>

  <xsd:simpleType name="non-empty-string">
    <xsd:restriction base="xsd:string">
      <xsd:minLength value="1" />
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="proxy">
    <xsd:sequence>
      <xsd:element name="host" type="xsd:string" />
      <xsd:element name="port" type="xsd:unsignedShort" nillable="true" />
      <xsd:element name="username" type="xsd:string" />
      <xsd:element name="password" type="xsd:string" />
      <xsd:element name="workstation" type="xsd:string" />
      <xsd:element name="domain" type="xsd:string" />
    </xsd:sequence>
    <xsd:attribute name="enable" use="required" type="xsd:boolean" />
  </xsd:complexType>

  <xsd:complexType name="asns">
    <xsd:sequence>
      <xsd:element name="endpoint" type="xsd:string" />
      <xsd:element name="platform-application-arn" type="xsd:string" />
      <xsd:choice>
        <xsd:sequence>
          <xsd:element name="access-key" type="xsd:string" minOccurs="1" />
          <xsd:element name="secret-key" type="xsd:string" minOccurs="1" />
          <xsd:element name="iam-role-arn" type="xsd:string" minOccurs="0" />
        </xsd:sequence>
        <xsd:element name="iam-role-arn" type="xsd:string" minOccurs="1" />
      </xsd:choice>
      <xsd:element name="fcm-project-id" type="xsd:string" minOccurs="0" />
      <xsd:element name="fcm-application-id" type="xsd:string" minOccurs="0" />
      <xsd:element name="fcm-api-key" type="xsd:string" minOccurs="0" />
      <xsd:element name="fcm-sender-id" type="xsd:string" minOccurs="0" />
      <xsd:element name="baidu-api-key" type="xsd:string" minOccurs="0" />
    </xsd:sequence>
    <xsd:attribute name="name" use="required" type="xsd:ID" />
  </xsd:complexType>

  <xsd:complexType name="fcm">
    <xsd:sequence>
      <xsd:element name="url" type="xsd:string" />
      <xsd:element name="project-id" type="xsd:string" />
      <xsd:element name="application-id" type="xsd:string" />
      <xsd:element name="api-key" type="xsd:string" />
      <xsd:choice>
        <xsd:element name="server-key" type="xsd:string" />
        <xsd:element name="credentials-file" type="tns:credentials-file" />
      </xsd:choice>
      <xsd:element name="sender-id" type="xsd:string" />
    </xsd:sequence>
    <xsd:attribute name="name" use="required" type="xsd:ID" />
  </xsd:complexType>

  <xsd:complexType name="push">
    <xsd:attribute name="type" use="required" type="tns:non-empty-string" />
    <xsd:attribute name="engine" use="required" type="tns:non-empty-string" />
  </xsd:complexType>

  <xsd:complexType name="credentials-file">
    <xsd:simpleContent>
      <xsd:extension base="xsd:string">
        <xsd:attribute name="secret-key" use="optional" type="xsd:string" default="___intra-mart___"/>
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>
</xsd:schema>

=== accelplatform/docker-stacks-cluster/data/juggling/project/conf/im-notice-mobile-config.xml
<?xml version="1.0" encoding="UTF-8"?>

<im-notice-mobile-config xmlns="http://www.intra-mart.jp/notice/mobile/config/im-notice-mobile-config"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.intra-mart.jp/notice/mobile/config/im-notice-mobile-config ../schema/im-notice-mobile-config.xsd">

    <proxy enable="false">
        <host></host>
        <port xsi:nil="true"></port>
        <username></username>
        <password></password>
        <workstation></workstation>
        <domain></domain>
    </proxy>

    <asns name="asns-apns">
        <endpoint>sns.ap-northeast-1.amazonaws.com</endpoint>
        <platform-application-arn></platform-application-arn>
        <access-key></access-key>
        <secret-key></secret-key>
    </asns>

    <asns name="asns-fcm">
        <endpoint>sns.ap-northeast-1.amazonaws.com</endpoint>
        <platform-application-arn></platform-application-arn>
        <access-key></access-key>
        <secret-key></secret-key>
        <fcm-project-id></fcm-project-id>
        <fcm-application-id></fcm-application-id>
        <fcm-api-key></fcm-api-key>
        <fcm-sender-id></fcm-sender-id>
    </asns>

    <asns name="asns-baidu">
        <endpoint>sns.ap-northeast-1.amazonaws.com</endpoint>
        <platform-application-arn></platform-application-arn>
        <access-key></access-key>
        <secret-key></secret-key>
        <baidu-api-key></baidu-api-key>
    </asns>

    <fcm name="fcm">
        <url>https://fcm.googleapis.com/v1/projects/%REPLACE_WITH_PROJECT_ID%/messages:send</url>
        <project-id></project-id>
        <application-id></application-id>
        <api-key></api-key>
        <credentials-file></credentials-file>
        <sender-id></sender-id>
    </fcm>

    <fcm name="legacy-fcm">
        <url>https://fcm.googleapis.com/fcm/send</url>
        <project-id></project-id>
        <application-id></application-id>
        <api-key></api-key>
        <server-key></server-key>
        <sender-id></sender-id>
    </fcm>

    <push type="android" engine="fcm" />
    <push type="ios" engine="asns-apns" />

    <max-push-subject-length>30</max-push-subject-length>
    <max-push-body-length>70</max-push-body-length>
</im-notice-mobile-config>
